######################## default configuration ####################
baseURL = "https://kisahkan.lamsz.id"
languageCode = "en"
title = "Kisahkan | Kisah - Kisah Islami"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Stories"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Android"
  URL = "https://play.google.com/store/apps/details?id=com.lamsz.kisahkan"
  weight = 3

  [[menu.main]]
  name = "iOS"
  URL = "https://www.apple.com/id/search/kisahkan"
  weight = 4

  # [[menu.main]]
  # name = "Privacy Policy"
  # URL = "terms-conditions"
  # weight = 5
  
  # [[menu.main]]
  # name = "Contact"
  # URL = "https://www.lamsz.id/"
  # weight = 6

  ############# footer menu #############
  [[menu.footer]]
  name = "Stories"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Android"
  URL = "https://play.google.com/store/apps/details?id=com.lamsz.kisahkan"
  weight = 3

  [[menu.footer]]
  name = "iOS"
  URL = "https://apps.apple.com/id/app/kisahkan/id1546698306"
  weight = 4

  [[menu.footer]]
  name = "Terms and Condition"
  URL = "terms-conditions"
  weight = 5

  [[menu.footer]]
  name = "Privacy Policy"
  URL = "faq"
  weight = 6

  [[menu.footer]]
  name = "Contact"
  URL = "https://www.lamsz.id/"
  weight = 7


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
#gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
#mapLatitude = "51.5223477"
#mapLongitude = "-0.1622023"
#mapMarker = "images/marker.png"
# Google Analitycs
#googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "081249251538"
email = "admin@lamsz.id"
location = "Yogyakarta, Indonesia"
# copyright
copyright = "| Copyright &copy; 2019 [Gethugothemes](https://gethugothemes.com) All Rights Reserved |"
# Snipcart Credentials
# snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
# currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook"
  link = "https://www.facebook.com/Lamsz-Indonesia-637063400258900"

  #  [[params.social]]
  # icon = "ti-twitter-alt"
  # link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "https://www.youtube.com/channel/UCE7b4n9BPEdXDe5CHttFcng/videos"

  [[params.social]]
  icon = "ti-instagram"
  link = "https://www.instagram.com/kisahkan.lamsz/"

  #  [[params.social]]
  #  icon = "ti-pinterest"
  #  link = "#"

  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io
